server: 
    port: 8001
spring: 
    application: 
       name: minroservicecloud-dept
eureka:
 client: 
    service-url: 
      defaultZone: http://localhost:7001/eureka/
 instance: 
       instance-id: minroservicecloud-dept:8001
       